name: my-first-workflow
# To get a trigger on every push
on: 
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:
  push:
    

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-22.04
    steps:
      - name: step 1
        run: |
          pwd
          ls -ltr
          hostname
      - name: Step 2     Checkout
        uses: actions/checkout@v6.1.0
      - name: Step 3
        run: |
          pwd
          ls -ltr
          hostname

          
    
